version: '3.6'
services:

  node:
    build: docker/nodejs
    depends_on:
      - php-fpm
    volumes:
      - "./:/www"
    networks:
      - laravel
  php-fpm:
    build: docker/php-fpm
    depends_on:
      - db
    volumes:
      - "./app:/www"
    environment:
      - "XDEBUG_CONFIG=remote_host=192.168.220.1 remote_enable=1"
      - "PHP_IDE_CONFIG=serverName=Docker"

    networks:
      - laravel

  nginx:
    image: nginx:1.16-alpine
    depends_on:
      - php-fpm
    ports:
      - "8100:80"
      - "8143:443"
    volumes:
      - "./:/www"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
    networks:
      - laravel

  db:
    image: postgres:12-alpine
    volumes:
      - ./docker/postgres/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DOCKER_DATABASE}
      - POSTGRES_USER=${DOCKER_USERNAME}
      - POSTGRES_PASSWORD=${DOCKER_PASSWORD}
    ports:
      - "8101:5432"
    networks:
      - laravel

  test-db:
    image: postgres:12-alpine
    volumes:
      - ./docker/postgres/postgres-test:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DOCKER_DATABASE_TEST}
      - POSTGRES_USER=${DOCKER_USERNAME}
      - POSTGRES_PASSWORD=${DOCKER_PASSWORD}
    ports:
      - "8102:5432"
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8103:8025"
    depends_on:
      - php-fpm
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
